// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARau0E_Bwi964pMVF2R1_XcSFdy7wxHoA',
    appId: '1:485209781835:web:6a397da78b4770ba707fce',
    messagingSenderId: '485209781835',
    projectId: 'e-commerce-website-a21c1',
    authDomain: 'e-commerce-website-a21c1.firebaseapp.com',
    storageBucket: 'e-commerce-website-a21c1.appspot.com',
    measurementId: 'G-T2Q6FND0KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcl2Hx1YomUs-ByYAflEbv8UTK30RJ-e0',
    appId: '1:485209781835:android:b8a5a687cb0a1e83707fce',
    messagingSenderId: '485209781835',
    projectId: 'e-commerce-website-a21c1',
    storageBucket: 'e-commerce-website-a21c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6S4UjEBcC2GX08E3EcbPrtywGC0RFaDQ',
    appId: '1:485209781835:ios:c599d6e205e6cd0e707fce',
    messagingSenderId: '485209781835',
    projectId: 'e-commerce-website-a21c1',
    storageBucket: 'e-commerce-website-a21c1.appspot.com',
    iosClientId: '485209781835-ketho5411ptk2bc7ucb5tc4v9hhk6sjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.tmdt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6S4UjEBcC2GX08E3EcbPrtywGC0RFaDQ',
    appId: '1:485209781835:ios:c599d6e205e6cd0e707fce',
    messagingSenderId: '485209781835',
    projectId: 'e-commerce-website-a21c1',
    storageBucket: 'e-commerce-website-a21c1.appspot.com',
    iosClientId: '485209781835-ketho5411ptk2bc7ucb5tc4v9hhk6sjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.tmdt',
  );
}
